version: "3.9"

services:
  employee_db:
    image: mysql:8.0
    container_name: employee_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   # root password
      MYSQL_DATABASE: employee_db  # database নাম
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  employee_web:
    build: .
    container_name: employee_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - employee_db
    environment:
      DB_NAME: employee_db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: employee_db
      DB_PORT: 3306

volumes:
  db_data:
